### ISSUE TITLE
The results on low light enhancement is strange

### ISSUE THREAD

**Issue by JuZiSYJ** [swz30/MIRNetv2#2]
1. The low light enhancement on 《[Lighting the Darkness in the Deep Learning Era](http://mc.nankai.edu.cn/ll/#)》is different from the results shown in this paper, especially on **LIME** and **Retinex-Net**.

![image](https://user-images.githubusercontent.com/38501523/167077716-331ffb62-7a72-4c8b-a7f6-d3057d15cce1.png)
![image](https://user-images.githubusercontent.com/38501523/167077863-392a80b5-46c1-490d-bd60-6875773dcb8f.png)

**Comment by swz30** [comment]
Hi @JuZiSYJ 

Please see Fig. 7 of [Kindling the Darkness: A Practical Low-light Image Enhancer paper](https://arxiv.org/pdf/1905.04161.pdf)

**Comment by JuZiSYJ** [comment]
Thanks！ But the results on  **LIME** and  **Retinex-Net** shown in most of the  low-light enhancement papers are normal.
