### ISSUE TITLE
help me！！！please！！！帮我看一眼可以吗？训练跑步起来啊！单卡单机！

### ISSUE THREAD

**Issue by Lz-2019317** [swz30/MIRNetv2#22]
报错如下：
`ModuleNotFoundError:` No module named 'basicsr'
这个basicsr是项目文件夹，导入为啥会报错啊？

`ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 28610) of binary: /home/xtzg/anaconda3/envs/pytorch1.1`

我的设置如下
train.sh中设置为：
`python -m torch.distributed.run --nproc_per_node=1 --master_port=4321 basicsr/train.py -opt $CONFIG --launcher pytorch`
yaml配置文件中也修改shuffle为false
`    # data loader
    use_shuffle: false     # true
    num_worker_per_gpu: 0  # 8
    batch_size_per_gpu: 1  # 8`

**Comment by zhangbaijin** [comment]
你好，单卡单机跑起来了吗

**Comment by Taslim-M** [comment]
Just drag the train.py out of basicsr if this problem happens
