### ISSUE TITLE
Query regarding element-wise summation

### ISSUE THREAD

**Issue by soumik12345** [swz30/MIRNetv2#23]
Hi, I am attempting to reproduce the results of this paper in Tensorflow. I have been referring to both the implementation details in mentioned in the [paper](https://www.waqaszamir.com/publication/zamir-2022-mirnetv2/zamir-2022-mirnetv2.pdf) and the code in this repository for my implementation. I have a doubt regarding the SKFF (selective kernel feature fusion) block. In the paper, it has been stated that in the Fuse operation in SKFF, the multi-scale feature maps are combined using element-wise summation, however, upon referring to [this line](https://github.com/swz30/MIRNetv2/blob/12f366a9c0d7759aff91118187650ba2ffc18df5/basicsr/models/archs/mirnet_v2_arch.py#L38) in the code, I found that it is being concatenated. Can you please clarify my doubt as to whether the features should be summed or concatenated?

cc: @swz30 @adityac8

**Comment by swz30** [comment]
Hi @soumik12345 

The first step of the ```fuse``` procedure starts from here (https://github.com/swz30/MIRNetv2/blob/12f366a9c0d7759aff91118187650ba2ffc18df5/basicsr/models/archs/mirnet_v2_arch.py#L41)

Before this line, all operations (concatenation, reshaping) is just to bring the L1 and L2 tensors in the correct shapes.

**Comment by soumik12345** [comment]
Thanks a lot for the clarification @swz30
