### ISSUE TITLE
question about RCBs number of each MRB

### ISSUE THREAD

**Issue by RuiWang-coder** [swz30/MIRNetv2#3]
hello my friends, your work was excellent, but i have a question: why you use 2 RCBs of each MRB in paper? In paper's Ablation Studies(table 11), 3 RCBs have better result than 2 RCBs.

**Comment by swz30** [comment]
Hi, 

Since our goal was to build a faster variant of MIRNet, we chose to have better computational efficiency (speed, params, etc.) at a loss of some accuracy.

**Comment by 1960923996** [comment]
> 

ok i see! Thanks for your quick reply~~~

**Comment by jiujiaolulule** [comment]
Hi，my dear friends!
Could you tell me what the SIDD Datasets you choose?  SIDD-Medium Dataset or SIDD-Full Dataset、Raw-RGB、sRGB?
I'm looking forward to your reply!

**Comment by RuiWang-coder** [comment]
sorry dude, i didn't use the SIDD Datasets yet,i thought may be you should create a new issue to ask the owner?

**Comment by swz30** [comment]
We use SIDD-Medium dataset. Here is the direct Google Drive link to download the training images https://drive.google.com/file/d/1UHjWZzLPGweA9ZczmV8lFSRcIxqiOVJw/view?usp=sharing

**Comment by jiujiaolulule** [comment]
oh! thank you very much! my dear friends!
