### ISSUE TITLE
Do images in MIRNetv2 need to be normalized to [0,1] or [-1, 1]? 

### ISSUE THREAD

**Issue by Spacei567** [swz30/MIRNetv2#7]
Hi, Can you tell me in MIRNet v1 and MIRNet v2 wheather the images need to be normalized?

**Comment by swz30** [comment]
Hi @Spacei567 

The images are normalized to [0,1]

https://github.com/swz30/MIRNetv2/blob/917505bfd0803626412641b088e88eb9e3b0cdf2/demo.py#L132

**Comment by Spacei567** [comment]
Thank you so much! And you research is excellent!
